name: parkinsons_tf_keras_const
data: 
  clinical: "./dataset/train_clinical_data.csv"
  proteins: "./dataset/train_proteins.csv"
  peptides: "./dataset/train_peptides.csv"
hyperparameters:
  global_batch_size: 32
  learning_rate: 0.0001
  topk_pooling_ratio: 0.8
  dropout: 0.5
records_per_epoch: 60000
searcher:
  name: single
  metric: val_loss
  smaller_is_better: true
  max_length:
    epochs: 20
entrypoint: model_def:ParkinsonsDisease
